[project]
name = "pplx-trial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.58.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
